language: scala
scala: 2.12.3
jdk: oraclejdk8

script: ./bin/runci.sh "$CI_TEST"
env:
  global:
    - TRAVIS_NODE_VERSION="8"
    - TRAVIS_YARN_VERSION="1.1.0"
  matrix:
    - CI_TEST: ;compile;test
    - CI_TEST: scripted
    - CI_TEST: scalafmt

cache:
  yarn: true
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier

before_install:
  # Install Node.js and yarn.
  - nvm install "$TRAVIS_NODE_VERSION"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$TRAVIS_YARN_VERSION"
  - export PATH=$HOME/.yarn/bin:$PATH

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

after_success:
- "./bin/ci-publish.sh"
