language: scala
scala: 2.12.4
jdk: oraclejdk8
sudo: false
dist: trusty

env:
  global:
    - TRAVIS_NODE_VERSION="8"
    - TRAVIS_YARN_VERSION="1.3.2"

matrix:
  include:
    - script: sbt ci-test
      env: CI_PUBLISH=true
      deploy:
        provider: script
        script: bash bin/ci-publish.sh
    - script: sbt ";^^$SCRIPTED_SBT_VERSION; scripted"
      env: SCRIPTED_SBT_VERSION="0.13.17"
    - script: sbt ";^^$SCRIPTED_SBT_VERSION; scripted"
      env: SCRIPTED_SBT_VERSION="1.0.4"
    - script: ./bin/scalafmt --test
      env: SCALAFMT=true

cache:
  yarn: true
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_install:
  # Install Node.js and yarn.
  - nvm install "$TRAVIS_NODE_VERSION"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$TRAVIS_YARN_VERSION"
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn config set ignore-engines true

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
